In [2]:
import numpy as np


In [3]:
nparray=np.array([1,2,3,4])
print(nparray)

[1 2 3 4]


In [4]:
print(nparray.ndim)

1


In [5]:
np2darray=np.array([[1,2,3],[4,5,6]])
print(np2darray)

[[1 2 3]
 [4 5 6]]


In [6]:
print(np2darray.ndim)

2


In [7]:
onesArray=np.ones(10)
print(onesArray)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [8]:
oneArray=onesArray.astype(int)
print(oneArray)

[1 1 1 1 1 1 1 1 1 1]


In [9]:
preFillArray=np.full(10,5)
print(preFillArray)

[5 5 5 5 5 5 5 5 5 5]


In [10]:
print(nparray*2)
list=[1,2,3,4]
print(list*2)

[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]
