In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])

In [4]:
a.shape

(5,)

In [5]:
b=np.array([[1,2,3,4],[5,6,7,8]])

In [6]:
b.shape

(2, 4)

In [7]:
c=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [9]:
newarr=c.reshape(4,3)

In [10]:
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
newarr.shape

(4, 3)

In [12]:
newarr2=c.reshape(2,3,2)

In [13]:
newarr2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [14]:
newarr2.shape

(2, 3, 2)

In [16]:
twoDarray=np.array([[1,2,3],[4,5,6]])

In [17]:
flattenArray=twoDarray.reshape(-1)

In [18]:
flattenArray

array([1, 2, 3, 4, 5, 6])