In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6,7])

In [5]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
print(arr[1:5])

[2 3 4 5]


In [8]:
print(arr[2:7])

[3 4 5 6 7]


In [10]:
print(arr[4:])

[5 6 7]


In [11]:
print(arr[1:6:2])

[2 4 6]


Slice 2D Array

In [13]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [14]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
print(b[1,1:4])

[7 8 9]


In [18]:
print(b[0,0:3])

[1 2 3]
