In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,3,4,5,8,5,10,20,21])

In [3]:
x=np.where(a==1)

In [4]:
x

(array([0], dtype=int64),)

In [5]:
y=np.where(a==4)

In [6]:
y

(array([4], dtype=int64),)

In [7]:
ans=np.where(a%2==0)

In [8]:
ans

(array([1, 4, 6, 8, 9], dtype=int64),)

In [9]:
np.short(a)

array([ 1,  2,  3,  3,  4,  5,  8,  5, 10, 20, 21], dtype=int16)

In [10]:
a2=np.array([44,12,90,75,55])

In [11]:
np.sort(a2)

array([12, 44, 55, 75, 90])

In [12]:
a3=np.array(['mango','papaya','apple'])

In [13]:
np.sort(a3)

array(['apple', 'mango', 'papaya'], dtype='<U6')